CREATE TABLE kanji (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  character CHAR(1) NOT NULL,
  on VARCHAR(255) NOT NULL,
  ontwo VARCHAR(255) NULL,
  kun VARCHAR(255) NOT NULL,
  kuntwo VARCHAR(255) NULL,
  stroke VARCHAR(2) NOT NULL,
  key VARCHAR(255) NOT NULL,
  significate VARCHAR(255) NOT NULL
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE TABLE hiragana (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  character CHAR(1) NOT NULL,
  stroke VARCHAR(2) NOT NULL
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE TABLE katakana (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  character CHAR(1) NOT NULL,
  stroke VARCHAR(2) NOT NULL
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE TABLE users (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL UNIQUE KEY,
  password VARCHAR(255) NOT NULL,
  firstname VARCHAR(255),
  lastname VARCHAR(255),
  role INT(1) NOT NULL DEFAULT (0)
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci;